version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    environment:
      VITE_API_HOST: ${VITE_API_HOST:-http://localhost:3000}
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
